---
title: "Building_Data_Visualization_Tools"
author: "Edmund Julian Ofilada"
date: "March 30, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# AWESOME course!

I just recently finished the course Building Data Visualization Course from Coursera. The course is taught by:    

<br>

- Roger D. Peng, PhD, Associate Professor Biostatistics 
    - Bloomberg School of Public Health
     
- Brooke Anderson,  Assistant Professor Environmental & Radiological Health Sciences
    - Colorado State University from Johns Hopkins University

<br>

I decided to create projects that will involve data from my country the Philippines and share them with everyone by placing them in this repository. 

## README.md

The README markdown document is displayed by default by GitHub whenever you visit a GitHub repository. The document you are reading now is the README.md file. It contains information about the content of this repo.

Each of the folders in this repository contain the files for my  projects. You can read a brief description of each project below and explore each project by exploring the directory.

You can click on the `index.md` file in each directory to display the file in html.  However, for some reason, my leaflet plots are not displaying properly. You may prepend the following URL to the URL of the html file to display them in github.io.

## Content 

- [Bohol_2013](/Building_Data_Visualization_Tools/Bohol_2013/)
     - This project depicts the double tragedy that the province of Bohol faced during year 2013.
     
- [Plotting_Earthquake_Data_in_R](/Building_Data_Visualization_Tools/Plotting_Earthquake_Data_in_R/)
     - Fun using R to plot earthquake data from the Philippines
     
- [Plotting_tcx_files](/Building_Data_Visualization_Tools/Plotting_tcx_files/)
     - If you're using wearble body sensors, here's an alternative way to look at your data, including GPS data in case your device can track geopositions.
     
- [Storms_in_Mindanao](/Building_Data_Visualization_Tools/Storms_in_Mindanao/)
     - Does Mindanao have fewer storms compare to the rest of the Philippines?

#### To download the content of this repository as a .zip file, click on the Download ZIP button. If you have a GitHub account, you can fork the content so you'll have a copy on your GitHub account.  